
###
POST http://localhost:3333/events
Content-Type: application/json
Accept: application/json

{
  "title": "Unite Summit",
  "details": "Um evento para quem é apaixonado por programacão",
  "maximumAttendees": 100
}

###

POST http://localhost:3333/events/b7e1ab68-d8b3-4e24-94db-41f876b4bcf3/attendees
Content-Type: application/json
Accept: application/json

{
  "name": "Paulo Marques",
  "email": "pm@pm.com"
}

###

GET http://localhost:3333/events/b7e1ab68-d8b3-4e24-94db-41f876b4bcf3
Accept: application/json